### ISSUE TITLE
add: more events to the list

### ISSUE THREAD

**Issue by noobshubham** [anubhavpulkit/Open-Source-Events#44]
add more events and hackathons to the so that this list is "one stop solution" for open source events

**Comment by AbcSxyZ** [comment]
To share some potential events to add, I have the following list in my calendar : 
- [International Conference on Open Source Software Systems](https://oss2022.github.io/index.html)
- LinuxCon/Open Source Summit 
- (#48)

Idk the repo policy for more national events, but for annual events in France : 
- [FlossCon](https://www.flosscon.org/)
- [Rencontres Professionnelles du Logiciel Libre](https://www.rpll.fr/)
- [Journées du Logiciel Libre](https://www.jdll.org/)
- [Rencontres Afrique France du Logiciel Libre](https://montpellibre.fr/rafll2022/index.html)
- [Capitole du Libre](https://capitoledulibre.org/)
- [Campus du libre](https://www.campus-du-libre.org/infos.php)
